### PR TITLE
Replaced 'react-native-fetch-blob' dependency with 'rn-fetch-blob'

### PR DESCRIPTION
**Pull request by adamivancza**

### CODE REVIEW

**Comment by gtebbutt** [comment]
@billmalarky Any chance this could be released? It'd be a major help to be able to get rid of the older dependency in a project I'm working on.

**Comment by adamivancza** [comment]
@gtebbutt meanwhile this PR is merged and released you could use my repo directly. Just insert this to your package.json file:

`"react-native-image-cache-hoc": "https://github.com/adamivancza/react-native-image-cache-hoc.git#0425d8375aa43edcad842ba029c1839da6e96576"`

**Comment by snobear** [comment]
ping @billmalarky - any chance you could merge and publish an updated npm package?

**Comment by billmalarky** [comment]
@snobear @adamivancza @gtebbutt The new package is entirely backwards compatible correct? I can't do a deep dive at this time but I can merge and run the tests and if everything passes I'll publish.

**Comment by adamivancza** [comment]
@billmalarky yeah it should be completely backward compatible as it's forked from the original library.

**Comment by snobear** [comment]
Yeah it is totally backward-compat per a few other projects that have switched over to `rn-fetch-blob`. 

Though you'll probably want to do a major version bump for `react-native-image-cache-hoc` (1.x.x to 2.x.x) as it'll be a breaking change since the dependency name (import statements) have changed, per this PR.

**Comment by adamivancza** [comment]
Yeah I agree with the above to treat this as a major version bump

**Comment by billmalarky** [comment]
Okay merged and published on NPM as version 2.0.0.

https://www.npmjs.com/package/react-native-image-cache-hoc

Thanks guys!

**Comment by snobear** [comment]
I was able to install it no prob. Thanks @billmalarky for your work on this project! And @adamivancza for the PR.

**Comment by billmalarky** [comment]
Excellent! Huge thanks to Adam.
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Pull request merged**
